"use client";
import { useEffect, useState } from "react";
import { Header } from "../../components/Header";

function getCountdown() {
  const now = new Date();
  const next = new Date(now);
  const daysUntilMonday = (8 - now.getDay()) % 7 || 7;
  next.setDate(now.getDate() + daysUntilMonday);
  next.setHours(0, 0, 0, 0);
  const diff = next.getTime() - now.getTime();
  const days = Math.floor(diff / (1000 * 60 * 60 * 24));
  const hours = Math.floor((diff / (1000 * 60 * 60)) % 24);
  const minutes = Math.floor((diff / (1000 * 60)) % 60);
  return { days, hours, minutes };
}

const winners = [
  { place: "1st", pct: "25%" },
  { place: "2nd", pct: "18%" },
  { place: "3rd", pct: "14%" },
  { place: "4th", pct: "10%" },
  { place: "5th", pct: "8%" },
  { place: "6th", pct: "7%" },
  { place: "7th", pct: "6%" },
  { place: "8th", pct: "5%" },
  { place: "9th", pct: "4%" },
  { place: "10th", pct: "3%" },
];

export default function Jackpot() {
  const [countdown, setCountdown] = useState(getCountdown());

  useEffect(() => {
    const interval = setInterval(() => setCountdown(getCountdown()), 60000);
    return () => clearInterval(interval);
  }, []);

  return (
    <main>
      <div className="page-hero">
        <Header active="Jackpot" />
        <div className="page-hero-content">
          <h1>💰 Weekly Jackpot</h1>
          <p>Predict. Compete. Earn.</p>
        </div>
      </div>

      <section
        style={{
          padding: "56px 24px",
          background: "linear-gradient(135deg, #123a5e 0%, #1c5c8f 100%)",
          color: "#fff",
          textAlign: "center",
        }}
      >
        <div style={{ maxWidth: 640, margin: "0 auto" }}>
          <p style={{ color: "rgba(255,255,255,0.75)", marginBottom: 24, lineHeight: 1.6 }}>
            Every week, you get a shot at the community jackpot — and the
            more XP you rack up, the better your odds. Place predictions,
            keep your check-in streak going, and climb the leaderboard to
            improve your chances.
          </p>

          <p style={{ fontSize: 40, fontWeight: 700, marginBottom: 8 }}>
            $250 USDC{" "}
            <span style={{ fontSize: 13, fontWeight: 400, color: "rgba(255,255,255,0.5)" }}>
              (preview)
            </span>
          </p>
          <p style={{ fontSize: 13, color: "rgba(255,255,255,0.6)", marginBottom: 32 }}>
            A percentage of all fees generated by Arcdiction bets feeds
            the weekly jackpot.
          </p>

          <p style={{ fontSize: 13, color: "rgba(255,255,255,0.6)" }}>
            Next distribution in {countdown.days}d {countdown.hours}h {countdown.minutes}m
          </p>
        </div>
      </section>

      <section style={{ padding: "48px 24px", maxWidth: 640, margin: "0 auto" }}>
        <h2 style={{ fontSize: 20, marginBottom: 8, textAlign: "center" }}>
          10 winners every week
        </h2>
        <p style={{ fontSize: 13, color: "#5f5e5a", textAlign: "center", marginBottom: 24 }}>
          The jackpot is split among the top 10 for the week, drawn with
          odds proportional to each person's XP.
        </p>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(110px, 1fr))",
            gap: 10,
          }}
        >
          {winners.map((w, i) => (
            <div
              key={i}
              style={{
                border: "1px solid #eee",
                borderRadius: 8,
                padding: "12px 8px",
                textAlign: "center",
              }}
            >
              <p style={{ fontWeight: 700, fontSize: 14, marginBottom: 2 }}>{w.place}</p>
              <p style={{ fontSize: 13, color: "#5f5e5a" }}>{w.pct}</p>
            </div>
          ))}
        </div>
      </section>

      <section style={{ padding: "0 24px 40px", maxWidth: 640, margin: "0 auto" }}>
        <p style={{ fontSize: 12, color: "#9aa5b1", textAlign: "center" }}>
          The jackpot amount is still an illustrative preview and the
          XP-weighted draw isn't automated yet — this is the planned
          mechanic, which will go live as the platform evolves.
        </p>
      </section>
    </main>
  );
}
